target_model:
  name: "gpt-3.5"
  provider: "openai"
  model_id: "gpt-3.5-turbo"
  temperature: 0.2
  max_tokens: 512
  api_key: "your-openai-api-key"  # Use environment variables in production!
  safety_thresholds:
    flagged: true
    confidence: 0.8
